export const productData = [
    {
        id: "6123def67890abc111456789",
        name: "OPPO Enco Buds 2",
        image: "https://pngimg.com/uploads/headphones/small/headphones_PNG7661.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Headphones",
        price: 8544,
        stock: 13,
        color: 'Safron',
    },
    {
        id: "6123def674780abc123456789",
        name: "Vivo V30 5G",
        image: "https://exstatic-in.vivo.com/Oz84QB3Wo0uns8j1/in/1695965611535/b0bfa258b03e0f3113ce4a071d4a68eb.png.webp",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Mobiles",
        price: 84544,
        stock: 65,
        color: 'Safron',
    },
    {
        id: "6123def47590abc123456789",
        name: "Tuters Blankets",
        image: "https://pngimg.com/uploads/blanket/small/blanket_PNG2.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Blankets",
        price: 844,
        stock: 213,
        color: 'Safron',
    },
    {
        id: "6258def67890abc123456789",
        name: "Realme Buds",
        image: "https://pngimg.com/uploads/headphones/small/headphones_PNG7640.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Headphones",
        price: 1544,
        stock: 0,
        color: 'Safron',
    },
    {
        id: "3693def67890abc123456789",
        name: "Sony 456 Headphones",
        image: "https://pngimg.com/uploads/headphones/small/headphones_PNG7637.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Headphones",
        price: 15544,
        stock: 23,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123456789",
        name: "Groto watch",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/files/Artboard1_239782ce-f17f-4d51-8ca3-54b21f8f38c0_medium.png?v=1702548702",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Watches",
        price: 4544,
        stock: 134,
        color: 'Safron',
    },
    {
        id: "6456def67890abc123456789",
        name: "Osomo new fabric",
        image: "https://pngimg.com/uploads/blanket/small/blanket_PNG15.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Blankets",
        price: 1244,
        stock: 0,
        color: 'Safron',
    },
    {
        id: "4563def67890abc123456789",
        name: "Ray Opticals",
        image: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e10118-c5-full-rim-round-eyeglasses_g_9109.jpg",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Glasses",
        price: 744,
        stock: 173,
        color: 'Safron',
    },
    {
        id: "6123def67890abc148656789",
        name: "Titan 340 Plus",
        image: "https://pngimg.com/uploads/watches/watches_PNG9855.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Watches",
        price: 8544,
        stock: 0,
        color: 'Safron',
    },
    {
        id: "6123def67890abc258456789",
        name: "USB 3.0 speed",
        image: "https://image01.oneplus.net/ebp/202312/20/1-m00-48-f8-ckvtlmwcuv2ay81caagjgqe_oeo406.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Cables",
        price: 544,
        stock: 137,
        color: 'Safron',
    },
    {
        id: "6123def67890abc147856789",
        name: "SAMSUNG Galaxy F15",
        image: "https://www.samsung.com/global/galaxy/main/images/banner_acc_s24-ultra.png",
        description: "Embark on an unrivaled mobile experience with the Samsung Galaxy F15, where innovation meets seamless functionality. Dive into a captivating visual journey with the sAMOLED display, bringing content to life with vibrant colors and sharp clarity. Whether you're streaming, gaming, or browsing, this display ensures an immersive and visually stunning experience that transcends expectations",
        category: "Mobiles",
        price: 75544,
        stock: 2,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123418389",
        name: "USB Cable",
        image: "https://ambraneindia.com/cdn/shop/products/1_c3a0d215-ddd7-48c3-8070-911fe2ac0f16_360x.webp?v=1657262637",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Cables",
        price: 244,
        stock: 1345,
        color: 'Safron',
    },
    {
        id: "6123def67890abc122796789",
        name: "Smart Watch",
        image: "https://flowbite.com/docs/images/products/apple-watch.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Watches",
        price: 1144,
        stock: 1312,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123454679",
        name: "OnePlus Nord 2",
        image: "https://motorolain.vtexassets.com/arquivos/ids/158549-500-auto?v=638309910977370000&width=500&height=auto&aspect=true",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Mobiles",
        price: 40000,
        stock: 17,
        color: 'Safron',
    },
    {
        id: "6123def67890abc122226789",
        name: "Silvi Analog Watch",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/files/Artboard1copy_41cb3a78-20c5-4c75-a793-849e26982a36_medium.png?v=1703659932",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Watches",
        price: 1544,
        stock: 138,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123444489",
        name: "Asus Tuf 8 GB",
        image: "https://flowbite.com/docs/images/products/imac.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Laptops",
        price: 88844,
        stock: 23,
        color: 'Safron',
    },
    {
        id: "6123def23390abc123456789",
        name: "Zunkurt Glasses",
        image: "https://static1.lenskart.com/media/desktop/img/Sep21/image179.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Glasses",
        price: 444,
        stock: 253,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123477789",
        name: "Cool Blanket",
        image: "https://pngimg.com/uploads/blanket/small/blanket_PNG19.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Blankets",
        price: 544,
        stock: 113,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123456159",
        name: "Apple IPhone 15",
        image: "https://flowbite.com/docs/images/products/iphone-12.png",
        description: "10 mm Large Titanized Driver (Stronger Bass); Enco Live Stereo Sound Effects (More Sound Effects); Up to 28 Hours of Listening Time (Longer Battery Life); AI Deep Noise Cancellation for Calls (Clear Calls); Binaural Low-latency with Bluetooth 5.2 Transmission (Faster and more Stable); Double-tap to Control Camera (More new Scenes).",
        category: "Mobiles",
        price: 98999,
        stock: 7,
        color: 'Safron',
    },
    {
        id: "6123def67890abc123999789",
        name: "Motorola G34 5G",
        image: "https://motorolain.vtexassets.com/arquivos/ids/158639/edge401.png?v=638380598194100000",
        description: "Fueled by the Snapdragon 695 5G octa-core processor and LPDDR4X memory, the Moto G34 5G delivers the speed required to maximize the capabilities of high-speed 5G networks. Experience exceptionally rapid mobile Internet speeds, leverage advanced video features and effortlessly handle all your tasks without any hassle.",
        category: "Mobiles",
        price: 45544,
        stock: 4,
        color: 'Safron',
    },
];

export const categories = [
    "Mobiles",
    "Watches",
    "Laptops",
    "Blankets",
    "Glasses",
    "Cables",
    "Headphones"
];